name: update

on:
  push:
    branches: [ master ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2.3.2
      with:
        ref: "master"
    
    - name: go setup
    - uses: actions/setup-go@v2.1.2
      with:
        go-version: "1.13"
    
    - name: git clone, run 
    - run: |
        git clone -b gh-pages https://github.com/sh0seo/lottery-history gh-pages
        go run main.go
    
    - name: copy and push
      env:
        GITHUB_USER: "sh0seo"
    - run: |
        cp index.md gh-pages/index.md
        cd gh-pages
        git config user.name "${GITHUB_USER}"
        git commit -am "Auto update"
        git push
