name: update

on:
  push:
    branches: [ master ]
  schedule:
    - cron:  '0 0 * * SUN'
      
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2.3.2
      with:
        ref: "master"
    
    - name: go setup
      uses: actions/setup-go@v2.1.2
      with:
        go-version: "1.13"
    
    - name: git clone, run 
      run: |
        git clone -b gh-pages https://github.com/sh0seo/lottery-history gh-pages
        go run main.go
    
    - name: Copy file
      uses: canastro/copy-action@0.0.2
      with:
        source: index.md
        target: gh-pages/index.md
      
    - name: GitHub Pages action
      uses: peaceiris/actions-gh-pages@v3.6.4
      with:
          github_token: ${{ secrets.TOKEN }}
          publish_dir: ./gh-pages
          user_name: sh0seo
          user_email: ssh0702@gmail.com 
          commit_message: "update auto"
          enable_jekyll: true 
